Repository RSA-Bots/RDA-Game, pull requests merged in 2022-04, with the labels that each got.

#6 Fix badge issue for lint ci
  README.md
Labels: sev: low, Review

#16 Workflow
  .github/contributing.md
  .github/issue_template/bug_report.md
  .github/issue_template/feature_request.md
  .github/pull_request_template.md
  README.md
  examples/framework/fusion.md
Labels: Review, Documentation

#17 Update pull_request_template.md
  .github/pull_request_template.md
Labels: sev: low, ver: build, Review, Documentation

#18 Knit Setup
  .gitignore
  default.project.json
  src/Client/Components/.gitkeep
  src/Client/Controllers/PlayerSparkleController.lua
  src/Client/KnitInit.client.lua
  src/Client/Main.client.lua
  src/Server/Components/SparkleEffect.lua
  src/Server/KnitInit.server.lua
  src/Server/Main.server.lua
  src/Server/Services/PlayerSparkleService.lua
  src/Shared/ModuleLoader.lua
  wally.toml
Labels: Completed

#21 Snippets
  .vscode/snippets.code-snippets
  wally.toml
Labels: sev: low, ver: build, Review, Documentation

#22 Initial implementation of label automation
  .github/workflows/board_labels.yml
Labels: sev: low, ver: minor, Review, Documentation

#25 Use Stylua formatting for snippets
  .vscode/snippets.code-snippets
Labels: Review, Documentation
